module AOC21
    include("Day 01/main.jl")
    include("Day 02/main.jl")
    include("Day 03/main.jl")
    include("Day 04/main.jl")
    include("Day 05/main.jl")
    include("Day 06/main.jl")
    include("Day 07/main.jl")
    include("Day 08/main.jl")
    include("Day 09/main.jl")
    include("Day 10/main.jl")
    include("Day 11/main.jl")
    include("Day 12/main.jl")
    include("Day 13/main.jl")
    include("Day 14/main.jl")
    include("Day 15/main.jl")
    include("Day 16/main.jl")
end